[package]
name = "curve_msg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
base64 = "0.22.1"
chacha20poly1305 = { version = "0.10.1", features = ["std"] }
hkdf = "0.12.4"
rand_core = "0.9.0"
serde = { version = "1.0.217", features = ["derive"] }
sha2 = "0.10.8"
x25519-dalek = { version = "2.0.1", features = ["serde", "static_secrets", "getrandom"] }
serde_json = "1.0.137"

[dev-dependencies]
criterion = { version = "2.7.2", package = "codspeed-criterion-compat" }


[[bench]]
name = "encryption"
harness = false
