[package]
name = "kychacha_crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
base64 = "0.22.1"
chacha20poly1305 = { version = "0.10.1", features = ["std"] }
hkdf = "0.12.4"
rand_core = "0.9.0"
serde = { version = "1.0.217", features = ["derive"] }
sha2 = "0.10.8"
serde_json = "1.0.138"
kyberlib = "0.0.6"
rand = "0.8.5"
zerocopy = "0.7.35"


[dev-dependencies]
criterion = { version = "2.7.2", package = "codspeed-criterion-compat" }


[[bench]]
name = "kyber_bench"
harness = false

[[bench]]
name = "chacha_bench"
harness = false
